### ISSUE TITLE
O2 PT1000 no selector in documentation

### ISSUE THREAD

**Issue by pmarkiewicz** [RobertLorincz/Orbiter-Toolboards#11]
I'm looking to buy O2 toolboard, documentation states that it's compatible with PT1000 but I don't see any resistor selector for PT1000

**Comment by RobertLorincz** [comment]
the selection is done only by klipper config

**Comment by pmarkiewicz** [comment]
so there is no way to change resistor value? it's a pity as this heavily
reduces precision of PT1000.

regards

**Comment by pmarkiewicz** [comment]
Good information, can you update documentation please?

**Comment by pmarkiewicz** [comment]
just toolboard documentation that there is 2.2k resistor.

**Comment by RobertLorincz** [comment]
It is written in the documentation check it...
![image](https://github.com/user-attachments/assets/eae458ed-0078-46c0-b42c-54b93d87f0e0)
