### ISSUE TITLE
Error temp measure

### ISSUE THREAD

**Issue by dimicel** [RobertLorincz/Orbiter-Toolboards#14]
The thermistor I have installed was measuring the temperature correctly when connected to the board. With the OrbitertoolO2, and using the same configuration (replacing the pin with the tool's pin), it shows a very low temperature, around 3 degrees and a bit, when the ambient temperature is about 20 degrees.

**Comment by RobertLorincz** [comment]
Have you configured the correct pull up resistor?

**Comment by dimicel** [comment]
Ok, That was the problem. I had crossed that line. Thnaks
