### ISSUE TITLE
schematic?

### ISSUE THREAD

**Issue by Fisheiyy** [RobertLorincz/Orbiter-Toolboards#2]
please post schematic for this toolhead board

**Comment by RobertLorincz** [comment]
Schematic is not planned to be released at this point. This is a complete new development, not a copy of existing boards. For now we do not want to make competitors job easy. I will release it in the future, but not now.

**Comment by qOtXqi** [comment]
@RobertLorincz Any news on the release of the schematics for the O2 now that the O2s is out? Thanks.

**Comment by RobertLorincz** [comment]
I do not think we will release the schematics soon.
