### ISSUE TITLE
Add dimensions to documentation

### ISSUE THREAD

**Issue by Norvat** [RobertLorincz/Orbiter-Toolboards#3]
![image](https://github.com/RobertLorincz/Orbiter-Toolboards/assets/62434024/8b21deb7-c79c-4ab7-947e-19b7cadbf935)

**Comment by RobertLorincz** [comment]
I shared .step files with complete dimension, what additional info would a 2D drawing add?

**Comment by Norvat** [comment]
Would just make it a bit easier for us that isn't going to use the board mounted to the orbiter to see the size and bolt pattern without opening a cad program :)
