### ISSUE TITLE
Klipper not recognising so3 board 

### ISSUE THREAD

**Issue by Naclifford** [RobertLorincz/Orbiter-Toolboards#7]
I’ve connected the board up, I’ve connected to klipper via ssh and the board isn’t listed in the usb section or to get the board to be recognised dfu. So I can’t go any further to flash the board

**Comment by RobertLorincz** [comment]
I recommend going through the documentation and flash klipper if its not already flashed on the micro.

**Comment by Naclifford** [comment]
After reinstalling klipper still no joy, so far it’s an expensive paperweight, I’m at a loss…

**Comment by RobertLorincz** [comment]
hard to me to debug your issue, since I have no idea about your setup or how is the board connected. Some basic question, the toolboard power indicator LED is ON, correct?
You have the USB cables and power cables connected as shown in the connection diagram? Did you try other USB ports as well?
